/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'on-secondary-container': '#600004',
        'error': '#ba1a1a',
        'surface-dim': '#d8dadc',
        'primary-container': '#131b2e',
        'on-background': '#191c1e',
        'surface-variant': '#e0e3e5',
        'surface-bright': '#f7f9fb',
        'inverse-surface': '#2d3133',
        'on-tertiary': '#ffffff',
        'tertiary-fixed': '#d3e4fe',
        'on-surface': '#191c1e',
        'secondary-fixed': '#ffdad5',
        'surface-container-high': '#e6e8ea',
        'on-primary': '#ffffff',
        'inverse-primary': '#bec6e0',
        'on-tertiary-fixed': '#0b1c30',
        'tertiary-fixed-dim': '#b7c8e1',
        'on-error': '#ffffff',
        'surface-container': '#eceef0',
        'on-primary-container': '#7c839b',
        'outline-variant': '#c6c6cd',
        'on-secondary-fixed-variant': '#910a0e',
        'on-error-container': '#93000a',
        'on-tertiary-container': '#75859d',
        'inverse-on-surface': '#eff1f3',
        'on-secondary-fixed': '#410002',
        'primary': '#000000',
        'on-surface-variant': '#45464d',
        'secondary-fixed-dim': '#ffb4aa',
        'surface': '#f7f9fb',
        'surface-container-highest': '#e0e3e5',
        'secondary': '#b32822',
        'secondary-container': '#fd5d50',
        'surface-container-lowest': '#ffffff',
        'error-container': '#ffdad6',
        'primary-fixed-dim': '#bec6e0',
        'background': '#f7f9fb',
        'on-primary-fixed-variant': '#3f465c',
        'surface-tint': '#565e74',
        'outline': '#76777d',
        'on-tertiary-fixed-variant': '#38485d',
        'surface-container-low': '#f2f4f6',
        'on-primary-fixed': '#131b2e',
        'tertiary': '#000000',
        'primary-fixed': '#dae2fd',
        'tertiary-container': '#0b1c30',
        'on-secondary': '#ffffff',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      spacing: {
        unit: '8px',
        'margin-mobile': '20px',
        gutter: '24px',
        'margin-desktop': '64px',
      },
      maxWidth: {
        'container-max': '1280px',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'headline-lg-mobile': ['28px', { lineHeight: '34px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-lg': ['36px', { lineHeight: '44px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'display-lg': ['60px', { lineHeight: '72px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
};
